Add initial battery docs
batteries-included/batteries-included pull request #1402
Opened 2024-12-30 08:47 UTC by jfaz1

This PR adds initial battery documentation, including:

- Getting started
- Projects
- VictoriaMetrics
- Grafana
- Jupyter Notebooks

2024-12-31 03:11 UTC, elliottneilclark commented on static/src/pages/docs/[...page].astro
> +    ['getting-started', 'projects', 'monitoring', 'pgvector'].includes(doc.slug)
Rather than this can we add category to the front matter and then filter based upon `category == 'gettingStartinged'` or something

2024-12-31 03:42 UTC, elliottneilclark requested changes
<img src="https://media3.giphy.com/media/OcCADMZgxt1VBvvyOM/giphy.gif"/>

2024-12-31 03:42 UTC, elliottneilclark commented on static/src/content/doc/getting-started.md
> +- **Security**: Enterprise-grade security with OAuth and mTLS built-in.
This is way too much wind up; Getting started is very few steps and we should be leaning into that.

2024-12-31 03:42 UTC, elliottneilclark commented on static/src/content/doc/getting-started.md
> +2. **Choose Your Environment**:
`Choose where and what to start your in environment/installation`. We're trying to use a little jargon as possible so it feels like the major choices are what kind of things you want to run and where. Tell us about those and then we start the rest.

2024-12-31 03:42 UTC, elliottneilclark commented on static/src/content/doc/getting-started.md
> +   and click "Create a new installation" to begin.
While we are pointing at the signup URL, this reads as the same as step 2: Create your installation.

2024-12-31 03:42 UTC, elliottneilclark commented on static/src/content/doc/projects.md
> +- Visit [Monitoring](/docs/monitoring) for metrics and logging.
Please add a section for Project Sync and mark it as coming soon. We are going to have a system for copying and syncing projects.

2025-01-02 08:50 UTC, jfaz1 commented on static/src/content/doc/projects.md
> +- Visit [Monitoring](/docs/monitoring) for metrics and logging.
I added the section using bits from this issue, let me know if that's the right idea: https://github.com/batteries-included/batteries-included/issues/1331

2025-01-02 16:37 UTC, elliottneilclark commented on static/src/content/doc/getting-started.md
> +   web services, AI tools, monitoring, etc.
I like this structure with no wind up. However I think each of the steps will likely still need more verbiage. For example in the last version you had a description about kind, AWS, or already running kubernetes cluster.  That was helpful I thought. Also a cut down screenshot (less than full screen, we can cut the sides and top off of the new install screen) showing how to choose where, and what to run would be really helpful.

2025-01-02 16:37 UTC, elliottneilclark commented on static/src/content/doc/getting-started.md
> +3. **Get Going**: We'll handle the setup and configuration automatically.
A screenshot of the single command line to run would be nice here.

2025-01-02 16:37 UTC, elliottneilclark commented on static/src/content/doc/getting-started.md
> +components.
Let's link the Slack, GitHub issues, and the rest of the docs here.

2025-01-03 18:43 UTC, elliottneilclark approved these changes
<img src="https://media4.giphy.com/media/DMSP9tmubnERsSC1rF/giphy.gif"/>

2025-01-03 19:04 UTC, merged